### ISSUE TITLE
error[E0161]: cannot move a value of type dyn... on rust 1.34

### ISSUE THREAD

**Issue by dckc** [Agoric/SwingSet.rs#1]
`cargo test` works fine [once I have rust 1.35 installed][clue], but in case anyone else tries with rust 1.34 (as provided by nix, for example), you might see:

```
error[E0161]: cannot move a value of type dyn std::ops::FnOnce(std::boxed::Box<dyn syscall::Syscall>) -> std::boxed::Box<dyn dispatch::Dispatch>: the size of dyn std::ops::FnOnce(std::boxed::Box<dyn syscall::Syscall>) -> std::boxed::Box<dyn dispatch::Dispatch> cannot be statically determined
   --> src/kernel.rs:188:28
    |
188 |             let dispatch = setup(Box::new(syscall));
    |                            ^^^^^

```

I'm not sure what's conventional about noting required rust versions, but as 1.35 came out just a month or two ago, maybe it's worth noting in README or CONTRIBUTING.

[clue]: https://stackoverflow.com/questions/30411594/cannot-move-a-value-of-type-fnonce-when-moving-a-boxed-function

**Comment by warner** [comment]
Oh, maybe the `<dyn $TRAIT>` stuff only got stablized in 1.35. I don't think there's any `Cargo.toml` syntax to let you specify a minimum version of `rustc`, but I'll add a note to the README about it. Right after I add a README :).
